version: "3.9"

networks:
  profunion_backend:
    driver: bridge

services:
  app: 
    container_name: profunion_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - profunion_backend